### ISSUE TITLE
Overlay menu steals terminal focus

### ISSUE THREAD

**Issue by tim-sueberkrueb** [lirios/terminal#11]
On Liri OS, when another terminal window is opened using the `Open new window` icon button, the terminal item of the original window doesn't respond to user keyboard input anymore.

**Comment by plfiorini** [comment]
This happens because clicking on the overflow menu will steal the focus from the terminal.
While I acknowledge this is not good you can click on the terminal to get the focus back: at least you can use the app until this problem is fixed.

**Comment by tim-sueberkrueb** [comment]
I tried to do that but it doesn't seem to work for me. I cannot get the terminal item of the original terminal react anymore.

**Comment by plfiorini** [comment]
It should do it since this morning :P

**Comment by tim-sueberkrueb** [comment]
Oh I see, never mind. I didn't build it from source and thought the package was up to date with git. Should check next time.
