### ISSUE TITLE
Improve Settings dialog look and feel

### ISSUE THREAD

**Issue by plfiorini** [lirios/terminal#14]
* List item left and right margins should take padding into account to appear attached to the border
* Vertical spacer to make the list compact
* No hover effect on list items
* Fixed settings dialog size

**Comment by V1shvesh** [comment]
Can I work upon this??

**Comment by plfiorini** [comment]
@V1shvesh yes

**Comment by V1shvesh** [comment]
I might be inconveniencing you a bit, but please can you elaborate the issue a bit more, and point me in the right direction?

**Comment by tim-sueberkrueb** [comment]
>  Also, I don't understand how to clone this project using repo.

Hey @V1shvesh, have you [tried to follow this guide](https://github.com/lirios/lirios/wiki/Contributor-Guide)? What didn't work?

**Comment by V1shvesh** [comment]
How do I get developer access?
Or do I use the `https` link(which is read-only)?

**Comment by plfiorini** [comment]
@V1shvesh use `https`, `ssh` is for people with direct write access to the repository

**Comment by V1shvesh** [comment]
This is what I got...
![lirios_009](https://user-images.githubusercontent.com/22243137/31052154-672628b2-a699-11e7-9ee6-a6a3d4873c01.png)

**Comment by V1shvesh** [comment]
Also `repo sync` has been going on in an endless spree of downloads

**Comment by V1shvesh** [comment]
And this project requires QBS of version 1.8, whereas I can only do 1.5.2 as I'm on Ubuntu 16.10...
Too many issues for me here :sob:

**Comment by tim-sueberkrueb** [comment]
@V1shvesh in general, Ubuntu 16.10 is no longer supported by Canonical, I recommend to update. As for Liri development, Ubuntu doesn't ship with recent enough versions of a lot of our dependencies so you would have to build a lot of them from source to setup. The easiest and recommended way to develop for Liri OS is on Arch Linux (as Liri OS is itself based on it).

**Comment by tim-sueberkrueb** [comment]
@V1shvesh note that the story is different for our *cross platform apps* (browser, text, calculator) which generally only depend on Qt and [fluid](https://github.com/lirios/fluid). They are therefore very easy to setup and work on not only on all Linux distros but also on Windows and Mac.
For *core apps* like terminal or files, I highly recommend to work on Arch. If you really want to work on specifically on terminal on Ubuntu, I would recommend to only setup the [dependencies that are needed](https://github.com/lirios/terminal/#dependencies) and clone the repo as usual without using the `repo` tool.

**Comment by V1shvesh** [comment]
@tim-sueberkrueb Thanks a lot for the advice! I think I should pay heed to it and change my distro to Arch

**Comment by tim-sueberkrueb** [comment]
@V1shvesh Yeah, I'm sorry, the advice I gave was based on me thinking `vibe` and therefore some KF5 dependencies being still required by terminal. So you should get this working on Ubuntu fairly hassle-free.

**Comment by V1shvesh** [comment]
almost broke my computer installing arch

**Comment by tim-sueberkrueb** [comment]
>almost broke my computer installing arch

Ugh :|

> so I guess I'll stick to Ubuntu for now.

Let us know when we can help with anything!

**Comment by V1shvesh** [comment]
@tim-sueberkrueb thanks a lot. But guess what?

I successfully installed ARCH!!!:grin:

Also, thanks a lot for the support guys. I'll get right to the issue once I set things up, still on the command line rn.
