### ISSUE TITLE
Navigate through the tabs with the keyboard

### ISSUE THREAD

**Issue by plfiorini** [lirios/terminal#15]
Shift+Left selects the previous tab, Shift+Right the next tab.

**Comment by tejas2005** [comment]
Can you please specify the issue a little more clearly/

**Comment by plfiorini** [comment]
Implement a couple of shortcut with the `Shortcut` QML component, to switch to the previous tab or the next tab.

Previous tab sequence: `Shift+Left`
Next tab sequence: `Shift+Right`

**Comment by plfiorini** [comment]
Closed via #17
