### ISSUE TITLE
"Papyros.Core" is not installed

### ISSUE THREAD

**Issue by alex285** [lirios/terminal#3]
After compile, when you try to run:

QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:25 module "Material.Extras" is not installed
qrc:/qml/main.qml:24 module "Material" is not installed
qrc:/qml/main.qml:26 module "Material.ListItems" is not installed
qrc:/qml/main.qml:28 module "Papyros.Core" is not installed
qrc:/qml/main.qml:25 module "Material.Extras" is not installed
qrc:/qml/main.qml:24 module "Material" is not installed
qrc:/qml/main.qml:26 module "Material.ListItems" is not installed
qrc:/qml/main.qml:28 module "Papyros.Core" is not installed
qrc:/qml/main.qml:25 module "Material.Extras" is not installed
qrc:/qml/main.qml:24 module "Material" is not installed
qrc:/qml/main.qml:26 module "Material.ListItems" is not installed
qrc:/qml/main.qml:28 module "Papyros.Core" is not installed
qrc:/qml/main.qml:25 module "Material.Extras" is not installed
qrc:/qml/main.qml:24 module "Material" is not installed
qrc:/qml/main.qml:26 module "Material.ListItems" is not installed
qrc:/qml/main.qml:28 module "Papyros.Core" is not installed

**Comment by zigapk** [comment]
@alex285 that is expected. Terminal was written for papyros and is currently being rewritten to fluid instead of qml-material. See feature/use_fluid and feature/use_fluid0 branches. (Although I don't know which state they are in - feature/use_fluid0 seems promissing)
