### ISSUE TITLE
Clicking new tab button twice in a row causes lock up

### ISSUE THREAD

**Issue by GitRASQ** [lirios/terminal#7]
Immediately after opening, if I click the new tab button twice the app stops responding and I have to send sigkill.

Arch Linux package - v 0.0.0.20170213-1

**Comment by plfiorini** [comment]
Note to self: the problem seems to be in the custom tab button implementation. Using a regular TabButton in Fluid doesn't seem to have problems

**Comment by plfiorini** [comment]
Doesn't seem to happen anymore with latest changes but I would like to find out what's going on exactly.

**Comment by oxy** [comment]
Bug randomly reappears in my testing as of 18d121a. Locks up sometimes, doesn't other times.
