### ISSUE TITLE
Doesn't launch in liri-shell

### ISSUE THREAD

**Issue by bpstrngr** [lirios/terminal#8]
I can start the app when in gnome on my arch installation, 
not when in a liri-session though. It's pinned on the launcher 
so it bounces a few, but nothing happens. 
Why can this be? Only thing separating 
me from sticking to a nice looking DE at last...

**Comment by hughwilliams94** [comment]
Just to note this is also affecting my installation on Arch.

**Comment by hughwilliams94** [comment]
Looking at messages when Terminal is launched from the console there appears to be issues starting kwalletd in my instance. If kwalletd5 is run manually prior to the terminal application it runs.

**Comment by plfiorini** [comment]
Seems to be fixed now, I built from sources and triggered a package build, this means users of the Arch binary packages should get the update.

Closing the issue, please tell me if you still have problems.
